services:
  mysql-order:
    image: mysql:8.0
    container_name: mysql-order-service
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_db
      MYSQL_USER: order_user
      MYSQL_PASSWORD: order_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_order_data:/var/lib/mysql

volumes:
  mysql_order_data: