services:
  mysql-order:
    image: mysql:8.0
    container_name: mysql-order-service
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_db
      MYSQL_USER: order_user
      MYSQL_PASSWORD: order_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_order_data:/var/lib/mysql
    networks:
      - investment-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "order_user", "-porder_pass"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-service:
    build:
      context: ../backend/order-service
      dockerfile: Dockerfile
    container_name: order-service
    environment:
      DB_URL: jdbc:mysql://mysql-order:3306/order_db
      DB_USERNAME: order_user
      DB_PASSWORD: order_pass
    ports:
      - "8081:8081"
    depends_on:
      mysql-order:
        condition: service_healthy
    networks:
      - investment-network

  mysql-settlement:
    image: mysql:8.0
    container_name: mysql-settlement-service
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: settlement_db
      MYSQL_USER: settlement_user
      MYSQL_PASSWORD: settlement_pass
    ports:
      - "3308:3306"
    volumes:
      - mysql_settlement_data:/var/lib/mysql
    networks:
      - investment-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "settlement_user", "-psettlement_pass"]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    container_name: localstack-investment
    ports:
      - "4566:4566"
    environment:
      SERVICES: sqs,sns,s3,eventbridge
      DEFAULT_REGION: us-east-1
    networks:
      - investment-network

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - investment-network

volumes:
  mysql_order_data:
  mysql_settlement_data:

networks:
  investment-network:
    driver: bridge