name: Build Microservices

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  gateway-service:
    name: Build gateway-service
    uses: ./.github/workflows/reusable-maven-build.yml
    with:
      service-path: backend/gateway-service

  order-service:
    name: Build order-service
    uses: ./.github/workflows/reusable-maven-build.yml
    with:
      service-path: backend/order-service

  settlement-service:
    name: Build settlement-service
    uses: ./.github/workflows/reusable-maven-build.yml
    with:
      service-path: backend/settlement-service

  notification-service:
    name: Build notification-service
    uses: ./.github/workflows/reusable-maven-build.yml
    with:
      service-path: backend/notification-service

  statement-service:
    name: Build statement-service
    uses: ./.github/workflows/reusable-maven-build.yml
    with:
      service-path: backend/statement-service